<form method="post" role="form">
    <br/>
    <select class="form-control" name="idEmpresa"  placeholder="Empresa" title="Ingrese Empresa">
        <option value></option>
        <?php foreach ($this->params["EMPRESAS"] as $key): ?>
            <option value="<?= $key["ID_EMPRESA"] ?>"><?= $key["NOMBRE"] ?></option>
        <?php endforeach; ?>
    </select>
    <br/>
    <select class="form-control col-sm-3" id='tipoMedicamentos' placeholder="Medicamentos" title="Ingrese medicamentos">
        <option value></option>
        <?php foreach ($this->params["TIPO_MEDICAMENTOS"] as $key): ?>
            <option costo='<?= $key["COSTO"] ?>'value="<?= $key["ID_TIPO_MEDICAMENTO"] ?>"><?= $key["CODIGO_BARRAS"] ?>=><?= $key["DESCRIPCION"] ?></option>
        <?php endforeach; ?>
    </select>
    <input  type="text" class="form-control col-sm-3" id='cantidad' value="" placeholder="Cantidad" title="Ingrese cantidad">
    <div class="form-inline"><input type="button" class="btn btn-info col-sm-3 btn-control-agregar" value="+"/> </div>
    <br>
    <table class="contenedor-forms table table-hover ">
        <tr>
            <th>Medicamento</th>
            <th>Cantidad</th>
            <th>Costo</th>
        </tr>
        <tr class="tr-original">            
        </tr>
    </table>
    <br/>
    <div class="alert alert-warning">
        <b>Total en este pedido : </b><div class="select-option-costo"></div>

    </div>
    <br/>
    <select class="form-control" name="idRepartidor"  placeholder="Persona repartidor" title="Ingrese persona repartidor">
        <option value></option>
        <?php foreach ($this->params["REPARTIDORES"] as $key): ?>
            <option value="<?= $key["IDENTIFICADOR"] ?>"><?= $key["NOMBRE"] ?></option>
        <?php endforeach; ?>
    </select>
    <input class="btn btn-info" type="submit" value="registrar pedido"/>
</form>