<!--<a href="<?= BASE ?>"><input type="button" value="volver" class="btn btn-info"/></a><br/><br/>-->

<table class="table table-hover">
    <?php
    foreach ($this->params["USER_DATA"] as $key => $value) {
        if ($key != "ID_ROL") {
            if ($key == "ESTADO") {
                echo "<tr> <td>$key</td><td>".(($value == 1) ? "SI" : "NO")."</td></tr>";
            }else{
                
                echo "<tr> <td>$key</td><td>$value</td></tr> ";
            }
        }else{
           
        }
    }
    ?>
</table>