<!--<div class="col-1-6">-->
    <div id="piechart" class="chart"></div>
<!--</div>-->
<?php //var_dump($this);?>
    <script type="text/javascript">
        google.setOnLoadCallback(cargarChart(<?= $this->params["json_usuarios_roles"]?>,"Usuarios roles")); 
        $(window).resize(function(){
            cargarChart(<?= $this->params["json_usuarios_roles"]?>,"Usuarios roles"); 
        })
    </script>
 