<!--<div class="col-1-6">-->
    <div id="piechart" class="chart"></div>
<!--</div>-->
<?php //var_dump($this);?>
    <script type="text/javascript">
        google.setOnLoadCallback(cargarChart2(<?= $this->params["json_tipo_medicamento"]?>,"Tipo medicamentos")); 
        $(window).resize(function(){
            cargarChart2(<?= $this->params["json_tipo_medicamento"]?>,"Tipo medicamentos"); 
        })
    </script>
 