<center>
	<a href="<?=BASE?>usuario/consultar" class="btn btn-info"><input class="btnHerramientas"  type="button" value="Consulta de datos"/></a><br/>
	<a href="<?=BASE?>usuario/modificar" class="btn btn-info" ><input  class="btnHerramientas" type="button" value="Modificar datos"/></a><br/>
	<a href="<?=BASE?>usuario/eliminar" class="btn btn-info"><input class="btnHerramientas"  type="button" value="Eliminar cuenta"/></a><br/>
	<a href="<?=BASE?>usuario/cerrarSesion" class="btn btn-info"> <input  class="btnHerramientas" type="button" value="Cerrar sesión "/></a><br/>	
</center>
