<!--<a href="<?=BASE?>"><input class="btn btn-info" type="button" value="volver"/></a><br/><br/>-->
<form method="post">
    <input type="text" name="codigoBarras" title="Código barras" placeholder="Código barras" class="form-control" />
    <br/>
    <input type="text" name="descripcion"  title="Descripción"  placeholder="Descripción"class="form-control" />
    
    <br/> 
    <input class="btn btn-info" type="submit" value="Crear tipo medicamento"/>
</form>
