<!--<a href="<?= BASE ?>"><input class="btn btn-info" type="button" value="volver"/></a><br/><br/>-->
<?php // var_dump($this->params);?>
<form method="post" role="form">
    <br/>
    <select class="form-control" name="idEmpresa"  placeholder="Empresa" title="Ingrese Empresa">
        <option value></option>
        <?php foreach ($this->params["EMPRESAS"] as $key): ?>
            <option value="<?= $key["ID_EMPRESA"] ?>"><?= $key["NOMBRE"] ?></option>
        <?php endforeach; ?>
    </select>
    <br/>

<!--    <div class="form-group  div-agregar">
        <div class="form-inline">
            <select class="form-control col-sm-3" name="tipoMedicamentos[]"  placeholder="Medicamentos" title="Ingrese medicamentos">
                <option value></option>
                <?php foreach ($this->params["TIPO_MEDICAMENTOS"] as $key): ?>
                    <option value="<?= $key["ID_TIPO_MEDICAMENTO"] ?>"><?= $key["CODIGO_BARRAS"] ?>=><?= $key["DESCRIPCION"] ?></option>
                <?php endforeach; ?>
            </select>
            <input  type="text" class="form-control col-sm-3" name="cantidad[]" value="" placeholder="Cantidad" title="Ingrese cantidad">
        </div>
    </div>-->
    <div class="form-inline"><input type="button" class="btn btn-info col-sm-3 btn-control-agregar" value="+"/></div>
<!--    <div class="contenedor-forms">

    </div>-->
<table class="contenedor-forms">
        <tr class="tr-original">
            <td>
                <select class="form-control col-sm-3" name="tipoMedicamentos[]"  placeholder="Medicamentos" title="Ingrese medicamentos">
                    <option value></option>
                    <?php foreach ($this->params["TIPO_MEDICAMENTOS"] as $key): ?>
                        <option value="<?= $key["ID_TIPO_MEDICAMENTO"] ?>"><?= $key["CODIGO_BARRAS"] ?>=><?= $key["DESCRIPCION"] ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td><input  type="text" class="form-control col-sm-3" name="cantidad[]" value="" placeholder="Cantidad" title="Ingrese cantidad"></td>
        </tr>
    </table>
    <br/>
    <br/>
    <select class="form-control" name="idRepartidor"  placeholder="Persona repartidor" title="Ingrese persona repartidor">
        <option value></option>
        <?php foreach ($this->params["REPARTIDORES"] as $key): ?>
            <option value="<?= $key["IDENTIFICADOR"] ?>"><?= $key["NOMBRE"] ?></option>
        <?php endforeach; ?>
    </select>
    <!--<input  type="text" class="form-control" name="idTipoMedicamento" value="<?php
    if (isset($_POST['idTipoMedicamento'])) {
        echo $_POST['idTipoMedicamento'];
    }
    ?>" placeholder="tipo Medicamento" title="Ingrese tipo medicamento">-->

    <input class="btn btn-info" type="submit" value="registrar pedido"/>
</form>